export enum SportEventMatchStatusEnum {
  NOT_STARTED = 'not_started',
  STARTED = 'started',
  FIRST_HALF = '1st_half',
  HALFTIME = 'halftime',
  SECOND_HALF = '2nd_half',
  AET = 'aet',
  AP = 'ap',
  ENDED = 'ended',
  POSTPONED = 'postponed',
  CANCELLED = 'cancelled',
  AWAITING_EXTRA_TIME = 'awaiting_extra_time',
  AWAITING_PENALTIES = 'awaiting_penalties',
  ABANDONED = 'abandoned',
  FIRST_EXTRA = '1st_extra',
  SECOND_EXTRA = '2nd_extra',
  EXTRA_TIME_HALFTIME = 'extra_time_halftime',
  PENALTIES = 'penalties',
  INTERRUPTED = 'interrupted',
  OVERTIME = 'overtime',
  START_DELAYED = 'start_delayed',
}
